steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/submissionmlgc-axeldavid/asclepius', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/submissionmlgc-axeldavid/asclepius']
images:
- 'gcr.io/submissionmlgc-axeldavid/asclepius'
